# Site settings
title: H. D. Ballesta
description: 'Business Card Page'
url: ''
baseurl: ''
profilepic: '/images/im.jpg'
bkimage: '/images/bk.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: H. D. Ballesta
  email: heverballesta@gmail.com
  github_username:  hdballestan
  linkedin_username:  hever-ballesta-6227b7199

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
